name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build docker image
              run: |
                docker build -t ${{ github.repository }} .
                docker images

