name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Build Docker Image
              run: |
                docker build -t ${{ github.repository }} .
                docker images

